### ISSUE TITLE
why the major version bump?

### ISSUE THREAD

**Issue by matthewmueller** [sindresorhus/object-assign#24]
doesn't seem like there were any breaking changes and it leads to a ridiculous number of warnings on NPM:

![img](https://cldup.com/BYZt8-Izh0.png)

**Comment by matthewmueller** [comment]
nvm, this is fixed by reinstalling, so npm actually loads an older version of assign for these dependencies. still not sure why this was a major bump though ;-)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/object-assign/releases/tag/v4.0.0

Semantically it was a breaking change since it now preserves the property order according to spec, which means the property order is different. People shouldn't depend on property order, but in reality many do. Last time I tried a minor for something I thought were minor I [broke half the internet](https://github.com/sindresorhus/object-assign/issues/15). So this was also to be overly cautious.

**Comment by matthewmueller** [comment]
ahh gotcha. okay good to know!
