### ISSUE TITLE
Using in typescript

### ISSUE THREAD

**Issue by KingWu** [sindresorhus/object-assign#35]
When compile, occur this error.

"Module 'objectAssign' resolves to a non-module entity and cannot be imported using this contrcut

**Comment by sindresorhus** [comment]
That's up to you to solve. This is just a normal node module.

**Comment by SamVerschueren** [comment]
Install the type definitions

**Comment by ericwooley** [comment]
This module does seem to be a pain to use using the es6 import syntax. I think the typings are wrong.

**Comment by SamVerschueren** [comment]
What's wrong with it? Example?

**Comment by ericwooley** [comment]
`typings install --save object-assign`
```
import assign from 'object-assign' // Error from TS: object assign has no default export
import {assign} from 'object-assign' // assign is undefined

// correct as the library is setup, but typescript thinks it's an object not a function.
// So it doesn't type properly.
import * as assign from 'object-assign' 

```

**Comment by BrianVallelunga** [comment]
I'm also experiencing issues with this. Is there a resolution? Why has this been closed? Ideally the node package would include the type definition in it.

**Comment by SamVerschueren** [comment]
I did a PR [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11709) to fix the issue.

> Ideally the node package would include the type definition in it.

If everyone would use TypeScript then yes, but some people couldn't care less. I personally use TypeScript (not all the time), but am submitting typedefs for my own library to DefinitelyTyped. If I start adding typedefs for TypeScript to my modules, I could as well add Flow type definitions to it. If tomorrow I stop using TypeScript and switch to Flow, I don't want to keep that typedef up to date myself because why should I? That's why I keep my own modules technology independent.

**Comment by SamVerschueren** [comment]
PR is merged in `DefinitelyTyped` so it should be good to go.
